version: "3"
services:
  app:
    build: ./app
    command: python -u app.py
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./app:/app
    network_mode: "host"

  mongoapp:
    build: ./mongoapp
    command: python -u __init__.py
    # ports:
    #   - "5000:5000"
    volumes:
      - ./mongoapp:/mongoapp
    network_mode: "host"
