version: "3"
services:
  app:
    build: ./app
    command: python -u app.py
    ports:
      - "8080:8080"
    environment:
      - DISPLAY
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./app:/app
    network_mode: "host"

  mongoapp:
    build: ./mongoapp
    command: python -u __init__.py
    ports:
      - "5000:5000"
    volumes:
      - ./mongoapp:/mongoapp
    network_mode: "host"
